// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cxxParentTItable
IntegerMatrix cxxParentTItable(SEXP sig);
RcppExport SEXP _multiseq_cxxParentTItable(SEXP sigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sig(sigSEXP);
    rcpp_result_gen = Rcpp::wrap(cxxParentTItable(sig));
    return rcpp_result_gen;
END_RCPP
}
// cxxSParentTItable
NumericVector cxxSParentTItable(SEXP sig);
RcppExport SEXP _multiseq_cxxSParentTItable(SEXP sigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sig(sigSEXP);
    rcpp_result_gen = Rcpp::wrap(cxxSParentTItable(sig));
    return rcpp_result_gen;
END_RCPP
}
// cxxreverse_pwave
NumericVector cxxreverse_pwave(SEXP estimate, SEXP pmat, SEXP qmat);
RcppExport SEXP _multiseq_cxxreverse_pwave(SEXP estimateSEXP, SEXP pmatSEXP, SEXP qmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type estimate(estimateSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pmat(pmatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type qmat(qmatSEXP);
    rcpp_result_gen = Rcpp::wrap(cxxreverse_pwave(estimate, pmat, qmat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiseq_cxxParentTItable", (DL_FUNC) &_multiseq_cxxParentTItable, 1},
    {"_multiseq_cxxSParentTItable", (DL_FUNC) &_multiseq_cxxSParentTItable, 1},
    {"_multiseq_cxxreverse_pwave", (DL_FUNC) &_multiseq_cxxreverse_pwave, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiseq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
