// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cxxParentTItable
IntegerMatrix cxxParentTItable(SEXP sig);
RcppExport SEXP multiseq_cxxParentTItable(SEXP sigSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type sig(sigSEXP);
    __result = Rcpp::wrap(cxxParentTItable(sig));
    return __result;
END_RCPP
}
// cxxSParentTItable
NumericVector cxxSParentTItable(SEXP sig);
RcppExport SEXP multiseq_cxxSParentTItable(SEXP sigSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type sig(sigSEXP);
    __result = Rcpp::wrap(cxxSParentTItable(sig));
    return __result;
END_RCPP
}
// cxxreverse_pwave
NumericVector cxxreverse_pwave(SEXP estimate, SEXP pmat, SEXP qmat);
RcppExport SEXP multiseq_cxxreverse_pwave(SEXP estimateSEXP, SEXP pmatSEXP, SEXP qmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type estimate(estimateSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pmat(pmatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type qmat(qmatSEXP);
    __result = Rcpp::wrap(cxxreverse_pwave(estimate, pmat, qmat));
    return __result;
END_RCPP
}
