# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxxParentTItable <- function(sig) {
    .Call('_multiseq_cxxParentTItable', PACKAGE = 'multiseq', sig)
}

cxxSParentTItable <- function(sig) {
    .Call('_multiseq_cxxSParentTItable', PACKAGE = 'multiseq', sig)
}

cxxreverse_pwave <- function(estimate, pmat, qmat) {
    .Call('_multiseq_cxxreverse_pwave', PACKAGE = 'multiseq', estimate, pmat, qmat)
}

